In [1]:
import numpy as np

In [14]:
a = np.array([(1,2,3,4),(5,6,7,8)])
b = np.array([1,2,3,4])
print(df)
print(df2)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4]


In [15]:
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362],
       [ 0.28366219,  0.96017029,  0.75390225, -0.14550003]])

## Ejercicio 2
Operaciones Aritemticas con Matrices

In [16]:
print(a.shape)
print(b.shape)

(2, 4)
(4,)


In [18]:
g = np.subtract(a,b)
print(g)

[[0 0 0 0]
 [4 4 4 4]]
